table FACT_Host
	lineageTag: c9cac734-e379-4c89-92fa-3e5beb90e06b

	measure 'TACS 등록률' =
			DIVIDE(
			    CALCULATE(COUNTROWS(FACT_TACS), FACT_TACS[TACS수용(OS)] = "Y"),
			    COUNTROWS(FACT_Host)
			)
		formatString: 0.0%
		lineageTag: b807a684-a63f-41e1-96ab-f2d041738ed5

	measure 정합성률 =
			DIVIDE(
			    CALCULATE(COUNTROWS(FACT_TACS_Matching), FACT_TACS_Matching[MatchStatus] = "MATCH"),
			    COUNTROWS(FACT_TACS_Matching)
			)
		formatString: 0.0%
		lineageTag: 6719f4d5-ab4e-43b6-a237-38cd50151668

	measure 'EDR 준수율' =
			DIVIDE(
			    CALCULATE(COUNTROWS(FACT_SecurityCompliance), FACT_SecurityCompliance[EDR설치] = "Y"),
			    COUNTROWS(FACT_SecurityCompliance)
			)
		formatString: 0.0%
		lineageTag: e1e573dd-4cef-439a-8d61-70189868ac79

	column HostID
		dataType: string
		isKey
		lineageTag: dbd54a3e-9f15-44a3-b86a-678c328b8178
		sourceColumn: HostID

	column 호스트명
		dataType: string
		lineageTag: 31aef988-73ce-4258-b010-8260afefadc8
		sourceColumn: 호스트명

	column 대표IP
		dataType: string
		lineageTag: 173fcfc9-24d4-47f0-9392-796c99db9dc2
		sourceColumn: 대표IP

	column 대표IP노마스킹
		dataType: string
		lineageTag: 7d32c924-5efe-4d72-ad37-3cb0b011f8fa
		sourceColumn: 대표IP노마스킹

	column OS
		dataType: string
		lineageTag: 88540181-d9bb-4b3c-8800-4e84da65361f
		sourceColumn: OS

	column OS계열
		dataType: string
		lineageTag: 5d815f83-b0d3-4b2b-8228-2e7242384795
		sourceColumn: OS계열

	column OS버전
		dataType: string
		lineageTag: 1a19402d-3668-47e3-831b-d1fd2040936e
		sourceColumn: OS버전

	column Platform
		dataType: string
		lineageTag: 55501be5-ea63-46ba-afa9-63a500358eff
		sourceColumn: Platform

	column CPU스펙
		dataType: string
		lineageTag: 5e6db532-1c43-4252-9d0c-8b04bb588d99
		sourceColumn: CPU스펙

	column CPU유형
		dataType: string
		lineageTag: 8382ad22-8271-4e53-bb2b-f46dda7d8321
		sourceColumn: CPU유형

	column 물리적CPU수
		dataType: int64
		lineageTag: 7d0f25b9-8ce8-4673-92b7-e1854e9b8aa2
		sourceColumn: 물리적CPU수

	column CPU물리Core수
		dataType: int64
		lineageTag: 6e66d066-efc9-40ba-85fb-ae4e28b64638
		sourceColumn: CPU물리Core수

	column CPU논리Core수
		dataType: int64
		lineageTag: 3c2d1667-b591-432e-bcb0-4eb89893764e
		sourceColumn: CPU논리Core수

	column 메모리용량MB
		dataType: int64
		lineageTag: d67519a3-a8c8-4b66-81bc-eb82052a2de8
		sourceColumn: 메모리용량MB

	column 호스트운용부서
		dataType: string
		lineageTag: 44f50d9f-f702-46c1-a35d-83af6360e299
		sourceColumn: 호스트운용부서

	column 호스트운용자
		dataType: string
		lineageTag: a2ab18c3-c729-473a-bc3b-fd4eb5ed29dc
		sourceColumn: 호스트운용자

	column PO부서
		dataType: string
		lineageTag: c7ecf2d2-b0be-4f37-962b-e8f7591d7887
		sourceColumn: PO부서

	column PO
		dataType: string
		lineageTag: 6d397aa6-6601-4076-b340-f9b9473e0f1d
		sourceColumn: PO

	column BA부서
		dataType: string
		lineageTag: c88fdfdb-fb92-4dc0-9abc-cf666d390f03
		sourceColumn: BA부서

	column BA
		dataType: string
		lineageTag: 2e112fb8-3a05-4c0f-8adf-725d02147015
		sourceColumn: BA

	column 표준서비스
		dataType: string
		lineageTag: b829673e-7e63-489d-b3b1-83de3f41ddf1
		sourceColumn: 표준서비스

	column 표준서비스명
		dataType: string
		lineageTag: b70af908-3dff-441f-847a-27e112424c1b
		sourceColumn: 표준서비스명

	column 단위서비스
		dataType: string
		lineageTag: 753e5ea1-0908-4e07-a727-77d32e0c3f75
		sourceColumn: 단위서비스

	column 단위서비스명
		dataType: string
		lineageTag: 0f2b0629-9be5-4a65-b3d8-a2ff4a556e04
		sourceColumn: 단위서비스명

	column 서비스등급
		dataType: string
		lineageTag: fd203366-756c-478e-aa73-fe94480c5eae
		sourceColumn: 서비스등급

	column VM수집방식상세
		dataType: string
		lineageTag: 23b6bd6d-c1a2-41a2-ad01-8a82d4472f1a
		sourceColumn: VM수집방식상세

	column 설비상태
		dataType: string
		lineageTag: ede3933c-95d2-4e8e-b2fc-806748a1c016
		sourceColumn: 설비상태

	column 최근접속일자
		dataType: dateTime
		lineageTag: 55df7df3-da17-4eef-aa8f-818ba1379352
		sourceColumn: 최근접속일자

	column 미접속일수
		dataType: int64
		lineageTag: 5e7487f1-587d-4b2c-8abd-ded32f325e3d
		sourceColumn: 미접속일수

	partition FACT_Host = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents(SourceFolder & "호스트조회_20260828.xlsx"), null, true),
				    Sheet = Source{[Item="호스트조회", Kind="Sheet"]}[Data],
				    Promoted = Table.PromoteHeaders(Sheet, [PromoteAllScalars=true]),
				    Typed = Table.TransformColumnTypes(Promoted, {
				        {"HostID", type text}, {"호스트명", type text}, {"대표IP", type text}, {"대표IP노마스킹", type text},
				        {"OS", type text}, {"OS계열", type text}, {"OS버전", type text}, {"Platform", type text},
				        {"CPU스펙", type text}, {"CPU유형", type text},
				        {"물리적CPU수", Int64.Type}, {"CPU물리Core수", Int64.Type}, {"CPU논리Core수", Int64.Type},
				        {"메모리용량MB", Int64.Type},
				        {"호스트운용부서", type text}, {"호스트운용자", type text},
				        {"PO부서", type text}, {"PO", type text}, {"BA부서", type text}, {"BA", type text},
				        {"표준서비스", type text}, {"표준서비스명", type text}, {"단위서비스", type text}, {"단위서비스명", type text},
				        {"서비스등급", type text}, {"VM수집방식상세", type text}, {"설비상태", type text},
				        {"최근접속일자", type date}, {"미접속일수", Int64.Type}
				    })
				in
				    Typed

