table FACT_Host
	lineageTag: c9cac734-e379-4c89-92fa-3e5beb90e06b

	measure 'TACS 등록률' =
			DIVIDE(
			    CALCULATE(COUNTROWS(FACT_TACS), FACT_TACS[TACS수용(OS)] = "Y"),
			    COUNTROWS(FACT_Host)
			)
		formatString: 0.0%
		lineageTag: b807a684-a63f-41e1-96ab-f2d041738ed5

	measure 정합성률 =
			DIVIDE(
			    CALCULATE(COUNTROWS(FACT_TACS_Matching), FACT_TACS_Matching[MatchStatus] = "MATCH"),
			    COUNTROWS(FACT_TACS_Matching)
			)
		formatString: 0.0%
		lineageTag: 6719f4d5-ab4e-43b6-a237-38cd50151668

	measure 'EDR 준수율' =
			DIVIDE(
			    CALCULATE(COUNTROWS(FACT_SecurityCompliance), FACT_SecurityCompliance[EDR설치] = "Y"),
			    COUNTROWS(FACT_SecurityCompliance)
			)
		formatString: 0.0%
		lineageTag: e1e573dd-4cef-439a-8d61-70189868ac79

	measure '총 호스트 수' = COUNTROWS(FACT_Host)
		formatString: #,0
		lineageTag: 33c22ead-72cd-4e35-9221-6b527d7ab127

	measure '총 장비 수' = COUNTROWS(FACT_Asset)
		formatString: #,0
		lineageTag: 4a440c59-e4e1-4561-858a-e643d2f3df3d

	measure 'TACS 대상 서버 수' = CALCULATE(COUNTROWS(FACT_Host), FACT_Host[TACS대상여부] = "Y")
		formatString: #,0
		lineageTag: 4f8ebd5b-0305-4560-889f-172a2865f254

	measure 'TACS 등록률(대상기준)' =
			DIVIDE(
			    CALCULATE(COUNTROWS(FACT_TACS), FACT_TACS[TACS수용(OS)] = "Y", FACT_Host[TACS대상여부] = "Y"),
			    CALCULATE(COUNTROWS(FACT_Host), FACT_Host[TACS대상여부] = "Y")
			)
		formatString: 0.0%
		lineageTag: b386d217-fd3b-4332-ba14-5f0ceacc25cc

	column HostID
		dataType: string
		isKey
		lineageTag: dbd54a3e-9f15-44a3-b86a-678c328b8178
		summarizeBy: none
		sourceColumn: HostID

		annotation SummarizationSetBy = Automatic

	column 호스트명
		dataType: string
		lineageTag: 31aef988-73ce-4258-b010-8260afefadc8
		summarizeBy: none
		sourceColumn: 호스트명

		annotation SummarizationSetBy = Automatic

	column 대표IP
		dataType: string
		lineageTag: 173fcfc9-24d4-47f0-9392-796c99db9dc2
		summarizeBy: none
		sourceColumn: 대표IP

		annotation SummarizationSetBy = Automatic

	column 대표IP노마스킹
		dataType: string
		lineageTag: 7d32c924-5efe-4d72-ad37-3cb0b011f8fa
		summarizeBy: none
		sourceColumn: 대표IP노마스킹

		annotation SummarizationSetBy = Automatic

	column OS
		dataType: string
		lineageTag: 88540181-d9bb-4b3c-8800-4e84da65361f
		summarizeBy: none
		sourceColumn: OS

		annotation SummarizationSetBy = Automatic

	column OS계열
		dataType: string
		lineageTag: 5d815f83-b0d3-4b2b-8228-2e7242384795
		summarizeBy: none
		sourceColumn: OS계열

		annotation SummarizationSetBy = Automatic

	column OS버전
		dataType: string
		lineageTag: 1a19402d-3668-47e3-831b-d1fd2040936e
		summarizeBy: none
		sourceColumn: OS버전

		annotation SummarizationSetBy = Automatic

	column Platform
		dataType: string
		lineageTag: 55501be5-ea63-46ba-afa9-63a500358eff
		summarizeBy: none
		sourceColumn: Platform

		annotation SummarizationSetBy = Automatic

	column CPU스펙
		dataType: string
		lineageTag: 5e6db532-1c43-4252-9d0c-8b04bb588d99
		summarizeBy: none
		sourceColumn: CPU스펙

		annotation SummarizationSetBy = Automatic

	column CPU유형
		dataType: string
		lineageTag: 8382ad22-8271-4e53-bb2b-f46dda7d8321
		summarizeBy: none
		sourceColumn: CPU유형

		annotation SummarizationSetBy = Automatic

	column 물리적CPU수
		dataType: int64
		lineageTag: 7d0f25b9-8ce8-4673-92b7-e1854e9b8aa2
		summarizeBy: sum
		sourceColumn: 물리적CPU수

		annotation SummarizationSetBy = Automatic

	column CPU물리Core수
		dataType: int64
		lineageTag: 6e66d066-efc9-40ba-85fb-ae4e28b64638
		summarizeBy: sum
		sourceColumn: CPU물리Core수

		annotation SummarizationSetBy = Automatic

	column CPU논리Core수
		dataType: int64
		lineageTag: 3c2d1667-b591-432e-bcb0-4eb89893764e
		summarizeBy: sum
		sourceColumn: CPU논리Core수

		annotation SummarizationSetBy = Automatic

	column 메모리용량MB
		dataType: int64
		lineageTag: d67519a3-a8c8-4b66-81bc-eb82052a2de8
		summarizeBy: sum
		sourceColumn: 메모리용량MB

		annotation SummarizationSetBy = Automatic

	column 호스트운용부서
		dataType: string
		lineageTag: 44f50d9f-f702-46c1-a35d-83af6360e299
		summarizeBy: none
		sourceColumn: 호스트운용부서

		annotation SummarizationSetBy = Automatic

	column 호스트운용자
		dataType: string
		lineageTag: a2ab18c3-c729-473a-bc3b-fd4eb5ed29dc
		summarizeBy: none
		sourceColumn: 호스트운용자

		annotation SummarizationSetBy = Automatic

	column PO부서
		dataType: string
		lineageTag: c7ecf2d2-b0be-4f37-962b-e8f7591d7887
		summarizeBy: none
		sourceColumn: PO부서

		annotation SummarizationSetBy = Automatic

	column PO
		dataType: string
		lineageTag: 6d397aa6-6601-4076-b340-f9b9473e0f1d
		summarizeBy: none
		sourceColumn: PO

		annotation SummarizationSetBy = Automatic

	column BA부서
		dataType: string
		lineageTag: c88fdfdb-fb92-4dc0-9abc-cf666d390f03
		summarizeBy: none
		sourceColumn: BA부서

		annotation SummarizationSetBy = Automatic

	column BA
		dataType: string
		lineageTag: 2e112fb8-3a05-4c0f-8adf-725d02147015
		summarizeBy: none
		sourceColumn: BA

		annotation SummarizationSetBy = Automatic

	column 표준서비스
		dataType: string
		lineageTag: b829673e-7e63-489d-b3b1-83de3f41ddf1
		summarizeBy: none
		sourceColumn: 표준서비스

		annotation SummarizationSetBy = Automatic

	column 표준서비스명
		dataType: string
		lineageTag: b70af908-3dff-441f-847a-27e112424c1b
		summarizeBy: none
		sourceColumn: 표준서비스명

		annotation SummarizationSetBy = Automatic

	column 단위서비스
		dataType: string
		lineageTag: 753e5ea1-0908-4e07-a727-77d32e0c3f75
		summarizeBy: none
		sourceColumn: 단위서비스

		annotation SummarizationSetBy = Automatic

	column 단위서비스명
		dataType: string
		lineageTag: 0f2b0629-9be5-4a65-b3d8-a2ff4a556e04
		summarizeBy: none
		sourceColumn: 단위서비스명

		annotation SummarizationSetBy = Automatic

	column 서비스등급
		dataType: string
		lineageTag: fd203366-756c-478e-aa73-fe94480c5eae
		summarizeBy: none
		sourceColumn: 서비스등급

		annotation SummarizationSetBy = Automatic

	column VM수집방식상세
		dataType: string
		lineageTag: 23b6bd6d-c1a2-41a2-ad01-8a82d4472f1a
		summarizeBy: none
		sourceColumn: VM수집방식상세

		annotation SummarizationSetBy = Automatic

	column 설비상태
		dataType: string
		lineageTag: ede3933c-95d2-4e8e-b2fc-806748a1c016
		summarizeBy: none
		sourceColumn: 설비상태

		annotation SummarizationSetBy = Automatic

	column 최근접속일자
		dataType: dateTime
		formatString: Long Date
		lineageTag: 55df7df3-da17-4eef-aa8f-818ba1379352
		summarizeBy: none
		sourceColumn: 최근접속일자

		variation 변형
			isDefault
			relationship: 786727a3-cfab-4ccc-a99c-8d0cf7998a79
			defaultHierarchy: LocalDateTable_468f33de-6a79-47f5-af01-2ef4868345f6.'날짜 계층'

		annotation UnderlyingDateTimeDataType = Date

		annotation SummarizationSetBy = Automatic

	column 미접속일수
		dataType: int64
		lineageTag: 5e7487f1-587d-4b2c-8abd-ded32f325e3d
		summarizeBy: sum
		sourceColumn: 미접속일수

		annotation SummarizationSetBy = Automatic

	column 서버관리_TACS등록여부
		dataType: string
		lineageTag: 3b4d2551-b60f-4779-b069-cb213c199e81
		summarizeBy: none
		sourceColumn: 서버관리_TACS등록여부

		annotation SummarizationSetBy = Automatic

	column 서비스구분
		dataType: string
		lineageTag: 7ec1f1b1-b6f9-4e7d-bf4c-c827166a0469
		sourceColumn: 서비스구분

	column TACS대상여부 =
			VAR IsLegacy = RELATED(DIM_OS[EOS대상여부]) = "Y"
			RETURN
			IF(
			    IsLegacy,
			    "N",
			    LOOKUPVALUE(
			        DIM_TACS_Scope_Rule[대상여부],
			        DIM_TACS_Scope_Rule[적용조건_서비스등급], FACT_Host[서비스등급],
			        DIM_TACS_Scope_Rule[적용조건_서비스구분], FACT_Host[서비스구분]
			    )
			)
		dataType: string
		lineageTag: cbdab916-75fa-4efe-96f2-a3c98dde6556

	column OS복합키 = FACT_Host[OS] & "|" & FACT_Host[OS버전]
		dataType: string
		isHidden
		lineageTag: 11254b95-c0ac-4aba-a33f-2e737198db71

	partition FACT_Host = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents(SourceFolder & "호스트조회_20260828.xlsx"), null, true),
				    Sheet = Source{[Item="호스트조회", Kind="Sheet"]}[Data],
				    Promoted = Table.PromoteHeaders(Sheet, [PromoteAllScalars=true]),
				    Typed = Table.TransformColumnTypes(Promoted, {
				        {"HostID", type text}, {"호스트명", type text}, {"대표IP", type text}, {"대표IP노마스킹", type text},
				        {"OS", type text}, {"OS계열", type text}, {"OS버전", type text}, {"Platform", type text},
				        {"CPU스펙", type text}, {"CPU유형", type text},
				        {"물리적CPU수", Int64.Type}, {"CPU물리Core수", Int64.Type}, {"CPU논리Core수", Int64.Type},
				        {"메모리용량MB", Int64.Type},
				        {"호스트운용부서", type text}, {"호스트운용자", type text},
				        {"PO부서", type text}, {"PO", type text}, {"BA부서", type text}, {"BA", type text},
				        {"표준서비스", type text}, {"표준서비스명", type text}, {"단위서비스", type text}, {"단위서비스명", type text},
				        {"서비스등급", type text}, {"VM수집방식상세", type text}, {"설비상태", type text},
				        {"최근접속일자", type date}, {"미접속일수", Int64.Type}, {"서버관리_TACS등록여부", type text}, {"서비스구분", type text}
				    })
				in
				    Typed

